game_version = '1.21.1'
mod_loader = 'neoforge'
mod_loader_version = '21.1.228'

[config]
# Path to a Java executable. If blank, a Mojang-provided JVM will be downloaded.
java = ''
# Extra arguments to pass to the JVM
java_args = ''
# Path to a custom JAR to use instead of the normal Minecraft client
custom_jar = ''
# Minimum game memory, in MB
min_memory = 512
# Maximum game memory, in MB
max_memory = 4096

# Game window resolution
[config.resolution]
width = 1708
height = 960
